version: "3"
services:
  caloriebasic-api:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: 'pm2-runtime src/app.js'
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/caloriebasic
      - PORT=8000
    image: caloriebasic-api
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/caloriebasic
      - /usr/src/caloriebasic/node_modules
  mongo:
    environment:
      MONGO_INITD_DATABASE: caloriebasic
    image: mongo:3.4
    hostname: mongo
    ports:
      - 27017:27017
    stop_grace_period: 2m

