version: "3"
services:
  caloriebasic-api:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: 'npm run serve'
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/caloriebasic
      - JWT_KEY=skdjf239FS84sfjjsFDSlf234jsiejr2DFi3j4j
      - PORT=3001
    image: caloriebasic-api
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/caloriebasic
      - /usr/src/caloriebasic/node_modules
  mongo:
    image: mongo:3.4
    environment:
      MONGO_INITD_DATABASE: caloriebasic
    hostname: mongo
    ports:
      - 27017:27017
    stop_grace_period: 2m