FROM node:10.6

RUN apt-get update -y && \
    useradd -m -d /home/cb cb

COPY ./src /usr/src/caloriebasic/src
COPY ./.env.example /usr/src/caloriebasic
COPY ./package-lock.json /usr/src/caloriebasic
COPY ./package.json /usr/src/caloriebasic
COPY ./yarn.lock /usr/src/caloriebasic

WORKDIR /usr/src/caloriebasic

RUN npm install && \
    npm -g install pm2 -g && \
    chown -R cb:cb /usr/src/caloriebasic

USER cb
